sonata-project/SonataNewsBundle

- Controller/Api/PostController.php
Prevent JSM from trying to parse Post entity when creating its meta
> Fix undefined index actualType exception

- Resources/views/Block/recent_comments.html.twig
- Resources/views/Block/recent_posts.html.twig
https://github.com/sonata-project/SonataAdminBundle/pull/2754
> Admin LTE 2.0

- Resources/translations/SonataNewsBundle.de.xliff
Added some missing translation keys
> German translation

- Entity/PostManager.php
- Tests/Entity/PostManagerTest.php
There is an error when showing the yearly or mothly archive.
This should fix #216
> Fix error when showing year archive

- Admin/PostAdmin.php
> Fix docblock

- Controller/PostController.php
- composer.json
Used here:
https://github.com/sonata-project/SonataNewsBundle/blob/master/Controller/PostController.php#L198-L205
> Missing SeoBundle dependency

- Block/RecentCommentsBlockService.php
- Block/RecentPostsBlockService.php
- Resources/translations/SonataNewsBundle.cs.xliff
- Resources/translations/SonataNewsBundle.de.xliff
- Resources/translations/SonataNewsBundle.en.xliff
- Resources/translations/SonataNewsBundle.es.xliff
- Resources/translations/SonataNewsBundle.fr.xliff
- Resources/translations/SonataNewsBundle.hu.xliff
- Resources/translations/SonataNewsBundle.ja.xliff
- Resources/translations/SonataNewsBundle.nl.xliff
- Resources/translations/SonataNewsBundle.pt_BR.xliff
- Resources/translations/SonataNewsBundle.ru.xliff
- Resources/translations/SonataNewsBundle.sk.xliff
- Resources/translations/SonataNewsBundle.sl.xliff
> Translate block labels

- composer.json
Looks like there where no breaking changes and tests pass
> Update serializer bundle dependency version to allow ^1.0

- Controller/PostController.php
Pr for https://github.com/sonata-project/SonataNewsBundle/issues/284
> Add missing parameters argument for calls to renderArchive

- Resources/translations/SonataNewsBundle.cs.xliff
- Resources/translations/SonataNewsBundle.de.xliff
- Resources/translations/SonataNewsBundle.en.xliff
- Resources/translations/SonataNewsBundle.es.xliff
- Resources/translations/SonataNewsBundle.fr.xliff
- Resources/translations/SonataNewsBundle.hu.xliff
- Resources/translations/SonataNewsBundle.ja.xliff
- Resources/translations/SonataNewsBundle.nl.xliff
- Resources/translations/SonataNewsBundle.pt_BR.xliff
- Resources/translations/SonataNewsBundle.ru.xliff
- Resources/translations/SonataNewsBundle.sk.xliff
- Resources/translations/SonataNewsBundle.sl.xliff
Fixes https://github.com/sonata-project/SonataNewsBundle/issues/215
Ping @rande @sagikazarmark
> Added missing comment status translation

- Resources/doc/reference/installation.rst
Pr for https://github.com/sonata-project/SonataNewsBundle/issues/272
> Fix installation doc comment ungenerated application bundle

- Document/PostManager.php
```markdown
- Added `Document\PostManager::findOneByPermalink` method
- Deprecate `Document\PostManager::findOneBySlug` method
```
Prepares the `Document/PostManager` for using the same interface like `Entity/PostManager` with the next major release.
> Deprecate PostManager::findOneBySlug for mongodb

- Document/CommentManager.php
- Document/PostManager.php
- Entity/CommentManager.php
- Entity/PostManager.php
- Model/CommentManagerInterface.php
- Model/PostManagerInterface.php
- UPGRADE-4.0.md
Depends on https://github.com/sonata-project/SonataNewsBundle/pull/307
```markdown
- Add the `findOneByPermalink` method to the `PostManagerInterface`
- Add the `getPager` method to the `PostManagerInterface`
- Add the `getPublicationDateQueryParts` method to the `PostManagerInterface`
- Removed `Document\PostManager::findOneBySlug` in favor of `Document\PostManager::findOneByPermalink` 
```
> Cleanup Managers

- Document/PostManager.php
- Entity/PostManager.php
```markdown
- Sync `PostManager` for document and entity repoitories
```
Both managers have a different behavior. Some parts were only added to the entity repository but should exist in the document repository too. 
Renamed internal variables.
> Sync document and entity PostManager

- Mailer/Mailer.php
I am targetting this branch, because i wan't only fix code style
```markdown
- Improve code style
```
> Use explode limit

- composer.json
I am targetting this branch, because this is only a slight BC break.
```markdown
- replaced full stack symfony dependencies with only used ones.
- removed `symfony/symfony` dependency
```
We don't need everything from symfony. Only the following classes are used:
```
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Processor;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use …
```
> Removed symfony full stack dependency

- Block/RecentCommentsBlockService.php
- Block/RecentPostsBlockService.php
I am targetting this branch, becausethis is BC
Fixed PHPDoc
> fixed PHPDoc

- Block/RecentCommentsBlockService.php
- Block/RecentPostsBlockService.php
- Controller/PostController.php
- DependencyInjection/SonataNewsExtension.php
- Resources/views/Admin/list_post_custom.html.twig
- composer.json
I am targetting this branch, because this is a patch.
```markdown
- The `sonata-project/block-bundle` is an optional dependency
- Fixed BlockBundle deprecation messages
- Fixed request service deprecation messages
- Fixed old center html tag
```
Fixed deprecated methods calls and html tags.
> Fixed deprecations

- Controller/PostController.php
- phpunit.xml.dist
I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see
> Remove exceptions from phpunit whitelist

- CHANGELOG.md
- UPGRADE-3.x.md
- src/Resources/translations/SonataNewsBundle.ru.xliff
> Manual merge

- src/Admin/PostAdmin.php
I am targeting this branch, because I got the error : `Could not load type "checkbox": class does not exist`
Closes #431 
```markdown
- Switch Field Type checkbox option to FQCN option for sf 4 compatibility
```
> Change field type format FQCN

- composer.json
- Add missing Symfony dependencies
- Upgrade some dependencies to improve build times on prefer-lowest
> Minor improvements on composer

- src/Resources/config/admin.xml
- src/Resources/config/block.xml
- src/Resources/config/mongodb.xml
- src/Resources/config/orm.xml
```markdown
- Make services public
```
> Make services public

- src/Action/CollectionPostArchiveAction.php
I am targeting this branch, because this is a hotfix.
Fixes #457
No changelog required, because this is just a patch for unreleased feature #457.
> Fixed wrong route parameter

- src/Action/DailyPostArchiveAction.php
- src/Resources/config/actions.xml
- src/Resources/config/routing/news.xml
- src/Resources/translations/SonataNewsBundle.de.xliff
- src/Resources/translations/SonataNewsBundle.en.xliff
- tests/DailyPostArchiveActionTest.php
I am targeting this branch, because this is BC if not tag is created before merging this.
```markdown
- Added a daily archive
```
There is a monthly and a yearly archive. This PR adds a daily archive.
>  Added daily archive 

- composer.json
- tests/Controller/Api/PostControllerTest.php
I am targeting this branch, because this is BC. 
```markdown
- Added support for latest `formatter-bundle`
```
> Added support for latest formatter-bundle

- src/Action/CollectionPostArchiveAction.php
- src/Action/DailyPostArchiveAction.php
- src/Action/MonthlyPostArchiveAction.php
- src/Action/PostArchiveAction.php
- src/Action/TagPostArchiveAction.php
- src/Action/ViewPostAction.php
- src/Action/YearlyPostArchiveAction.php
```markdown
- SEO: Append title instead of replacing it
```
Use the action title, but append the general seo title as suffix.
> SEO: Append title instead of replacing it

- composer.json
- docs/reference/installation.rst
Doctrine supports json natively since doctrine/dbal 2.6.0
> Remove reference to the json type

- src/Block/RecentCommentsBlockService.php
- src/Block/RecentPostsBlockService.php
No changelog required, because it fixes the unreleased #500 PR.
> Fixed missing class import

- src/Admin/CommentAdmin.php
- src/Admin/PostAdmin.php
- src/Block/Breadcrumb/BaseNewsBreadcrumbBlockService.php
- src/Block/Breadcrumb/NewsArchiveBreadcrumbBlockService.php
- src/Block/Breadcrumb/NewsPostBreadcrumbBlockService.php
- src/Block/RecentCommentsBlockService.php
- src/Block/RecentPostsBlockService.php
- src/Command/SynchronizeCommentsCountCommand.php
- src/DependencyInjection/Configuration.php
- src/Document/BasePost.php
- src/Document/PostManager.php
- src/Entity/BasePost.php
- src/Entity/BasePostRepository.php
- src/Entity/CommentManager.php
- src/Entity/PostManager.php
- src/Form/Type/CommentStatusType.php
- src/Form/Type/CommentType.php
- src/Mailer/Mailer.php
- src/Model/Blog.php
- src/Model/Comment.php
- src/Model/Post.php
- src/Model/PostInterface.php
- src/Permalink/CollectionPermalink.php
- src/Permalink/DatePermalink.php
- src/Serializer/PostSerializerHandler.php
- src/SonataNewsBundle.php
- src/Status/CommentStatusRenderer.php
- src/Twig/Extension/NewsExtension.php
- src/Util/HashGenerator.php
```markdown
- Match PHPDoc with doctrine model 
- Remove superfluous PHPDoc 
```
> Use more specific PHPDoc

- src/Model/Post.php
- src/Model/PostInterface.php
```markdown
- Match PHPDoc with doctrine model 
```
> Match PHPDoc with doctrine model 

- src/Model/CommentInterface.php
- src/Model/PostInterface.php
There is no need for a specific type. It could be an integer, string or UUID.
```markdown
- Changed id type to mixed
```
> Changed id type to mixed

- docs/reference/api.rst
Hello. This couple lines of code answers for question "Why I've got an empty JSON response?". I hope it can save time to beginners (like me).
> Api doc serializer example

- src/Action/ViewPostAction.php
I am targeting this branch, because this is a fixup of #459
```markdown
- Fix missing call to isVisible
```
> Fix missing call to isVisible

- composer.json
- tests/Entity/CommentManagerTest.php
- tests/Entity/PostManagerTest.php
The class was deprecated, plus that fixes the build.
> Use entity manager mock factory trait

- src/Entity/CommentManager.php
I am targeting this branch, because it is fix for mssql support - BC.
Part of  https://github.com/sonata-project/dev-kit/issues/689
```markdown
- fixed sql to work with mssql
```
> Add mssql support

- docs/reference/api.rst
- src/Controller/Api/PostController.php
- src/Entity/BasePostRepository.php
- src/Resources/config/doctrine_mongodb.xml
Replace references to `Application\` namespace.
I am targeting this branch, because this change respects BC.
Related to https://github.com/sonata-project/SonataNewsBundle/pull/612#pullrequestreview-459115317, #601.
This PR was requested at https://github.com/sonata-project/SonataNewsBundle/pull/612#pullrequestreview-459115317, but contrary to what I've understood there, fortunately the imported `Post` class wasn't being used in the Swagger definition.
For this reason, I consider this change "pedantic".
I'm not a user of this bundle, but I guess this change should have been made at #601.
Regarding this, I've found [some other occurrences](https://github.com/search?q=%22Application%5CSonata%5CNewsBundle%22+repo%3Asonata-project%2FSonataNewsBundle&type=Code) for the `Application\` namespace. …
> Replace references to `Application\` namespace

- composer.json
- src/Controller/Api/CommentController.php
- src/Controller/Api/PostController.php
- src/Resources/config/routing/api.xml
- src/Resources/config/routing/api/comment.xml
- src/Resources/config/routing/api/post.xml
- tests/App/AppKernel.php
- tests/App/config/config.yaml
- tests/App/config/routes.yaml
- tests/Functional/RoutingTest.php
Allow "friendsofsymfony/rest-bundle:^3.0".
I am targeting this branch, because these changes respect BC.
```markdown
- Added support for "friendsofsymfony/rest-bundle:^3.0"
- support for deprecated "rest" routing type in favor for xml
```
> Allow "friendsofsymfony/rest-bundle:^3.0"

- composer.json
- src/Action/AbstractPostArchiveAction.php
- src/Action/CollectionPostArchiveAction.php
- src/Action/DailyPostArchiveAction.php
- src/Action/MonthlyPostArchiveAction.php
- src/Action/TagPostArchiveAction.php
- tests/DailyPostArchiveActionTest.php
```markdown
- Remove translator deprecations
```
> Remove translator deprecations

- src/Resources/translations/SonataNewsBundle.nl.xliff
updates Dutch translations
I am targeting this branch, because it updates a translation
```markdown
- Updates Dutch translations
```
> updates Dutch translations

- composer.json
- src/Entity/CommentManager.php
- tests/Document/CommentManagerTest.php
- tests/Document/PostManagerTest.php
- tests/Entity/CommentManagerTest.php
- tests/Entity/PostManagerTest.php
I am targeting this branch, because this feature is BC.
```markdown
- Addded support for `doctrine/persistence` 2
```
> Add support for doctrine/persistence 2
