sonata-project/SonataNewsBundle

- Resources/views/Admin/list_post_custom.html.twig
I've ACL permissions setup,
I've posts with images, but if the current user is only ```VIEW``` granted on a post, he cannot view the post's image.
**Before**
**After**
> Correct permission check for images on posts list

- Admin/CommentAdmin.php
- Admin/PostAdmin.php
- Resources/translations/SonataNewsBundle.cs.xliff
- Resources/translations/SonataNewsBundle.de.xliff
- Resources/translations/SonataNewsBundle.en.xliff
- Resources/translations/SonataNewsBundle.es.xliff
- Resources/translations/SonataNewsBundle.fr.xliff
- Resources/translations/SonataNewsBundle.hu.xliff
- Resources/translations/SonataNewsBundle.ja.xliff
- Resources/translations/SonataNewsBundle.nl.xliff
- Resources/translations/SonataNewsBundle.pt_BR.xliff
- Resources/translations/SonataNewsBundle.ru.xliff
- Resources/translations/SonataNewsBundle.sk.xliff
- Resources/translations/SonataNewsBundle.sl.xliff
Removed duplicate translation for ``CommentAdmin`` groups and renamed the ``PostAdmin`` group labels.
> use translation keys for admin group names

- Entity/PostManager.php
- Permalink/PermalinkInterface.php
When using an invalid permalink format the ``\InvalidArgumentException`` is not handled and thrown to the front.
> Return empty post when there is a permalink exception

- Entity/PostManager.php
Closes #268 
Replaces #269
```markdown
- Fixed showing only one tag while filtering archive by tag
```
While showing a news archive for a tag, only that tag was displayed in the post list.
> Fixed showing only one tag while filtering archive by tag

- Admin/CommentAdmin.php
- Admin/PostAdmin.php
- composer.json
```markdown
- Fix deprecated usage of `Admin` class
```
The `Admin` class is deprecated since SonataAdminBundle `3.1`
> use AbstractAdmin instead of deprecated Admin class

- Controller/PostController.php
- Resources/views/Post/comment_form.html.twig
I am targetting this branch, because this a minor change.
```markdown
- Replaced html `form` element with twig function
```
This decouples the business logic from the layout.
> Use twig blocks for form rendering

- composer.json
I am targetting this branch, because this is a fix for development only.
StyleCI wouldn't run, because the dependency was added to the `conflict` section instead of `require-dev`.
> Fixed wrong StyleCI Bridge composer section

- Admin/CommentAdmin.php
- Admin/PostAdmin.php
- composer.json
I am targetting this branch, because this is a BC fix.
```markdown
- Fixed duplicate translation in tab menu
```
Since the 3.4 release of the admin bundle, the menu items are translated in the twig templates by the knp menu bundle.
> Fixed duplicate translation in tab menu

- Form/Type/ApiCommentType.php
- Form/Type/ApiPostType.php
- Resources/config/api_form.xml
- SonataNewsBundle.php
I am targetting this branch, because it is the stable branch.
```markdown
- add missing configuration to make the CoreBundle's FormHelper works properly
```
Fix missing code to make the FormHelper works properly, this affect the sonata's REST API.
> fix missing configuration to use the CoreBundle's FormHelper

- Resources/doc/reference/installation.rst
I am targetting this branch, because this is about documentation
See http://stackoverflow.com/questions/40206041/install-sonata-news-bundle-composer-error
The optional instructions still do not work, but at least the basic bundle can be installed.
> Recommend stable versions

- .travis.yml
- composer.json
I am targetting this branch, because I notice a dev-kit master build did not pass.
Closes #341 
This is about the unit test suite, so it's pedantic (fix in the test suite the user doesn't care). No need for a changelog.
Takes #341 , and adds a requirement for sonata core bundle `^3.0.2`, which provides this commit : https://github.com/sonata-project/SonataCoreBundle/commit/5ce8eb6df8f9a2bfe94a625284a05a14ec1d5970
I tried cherry-picking the other commit from the dev-kit PR, but couldn't (no changes). I didn't understand why but we'll see if the result seems ok.
> Fix broken build

- Document/PostManager.php
- Entity/PostManager.php
I am targetting this branch, because this is a bugfix.
```markdown
- the method `PostManager::findOneBySlug` will return null if the permalink couldn't be found
- Fixed throwing doctrine exception on invalid permalink
```
If you try to call the view action in the [PostController](https://github.com/sonata-project/SonataNewsBundle/blob/3.x/Controller/PostController.php#L171), it will throw a `Doctrine\ORM\NoResultException` if the permalink is invalid or could not been found., so the null check in the same method will never be called.
> Allow null result for PostManager::findOneBySlug

- Tests/Entity/CommentManagerTest.php
- Tests/Entity/PostManagerTest.php
- composer.json
I am targetting this branch, because this is BC.
```markdown
- Fixed pager test with DatagridBundle 2.2.1
```
DatagridBundle change from `getRootAlias` to `getRootAliases`
> Fixed tests

- composer.json
I am targetting this branch, because this is a patch.
```markdown
- Added missing swiftmailer dependency
```
This classed is used here: https://github.com/sonata-project/SonataNewsBundle/blob/3.x/Mailer/Mailer.php#L43
> Added missing swift mailer dependency

- Tests/Controller/Api/CommentControllerTest.php
- Tests/Controller/Api/PostControllerTest.php
- Tests/Document/CommentManagerTest.php
- Tests/Document/PostManagerTest.php
- Tests/Entity/CommentManagerTest.php
- Tests/Entity/PostManagerTest.php
- Tests/Model/BaseModelTest.php
- Tests/Model/CommentTest.php
- Tests/Model/PostTest.php
- Tests/PHPUnit_Framework_TestCase.php
- Tests/Permalink/CollectionPermalinkTest.php
- Tests/Permalink/DatePermalinkTest.php
I am targetting this branch, because this is for tests only.
The method `getMock` is deprecated.
> Removed deprecated getMock in unit tests

- Block/Breadcrumb/NewsPostBreadcrumbBlockService.php
- Block/RecentPostsBlockService.php
- Command/SynchronizeCommentsCountCommand.php
- Controller/Api/CommentController.php
- Controller/Api/PostController.php
- Controller/PostController.php
- DependencyInjection/SonataNewsExtension.php
- Document/BasePost.php
- Document/CommentManager.php
- Document/PostManager.php
- Entity/BasePostRepository.php
- Entity/PostManager.php
- Mailer/Mailer.php
- Model/Blog.php
- Model/Comment.php
- Model/CommentInterface.php
- Model/Post.php
- Model/PostInterface.php
- Status/CommentStatusRenderer.php
- Tests/Model/BaseModelTest.php
- Tests/Model/CommentTest.php
- Tests/Model/PostTest.php
- Twig/Extension/NewsExtension.php
I am targetting this branch, because this are pedantic changes.
```markdown
- Added missing `RecentPostsBlockService::$adminPool` parameter
- Added missing `NewsExtension::$blog` parameter
- Removed dead parameters in method calls
- Fixed wrong or missing PHPDoc
- Fixed return null value instead of void in `PostController::getSeoPage`
- Fixed return null value instead of void in `PostManager::findOneByPermalink`
- Fixed return null value instead of void in `CommentStatusRenderer::getStatusClass`
```
Fixed some pedantic stuff.
> Some fixes

- Document/PostManager.php
- Entity/PostManager.php
- Tests/Entity/PostManagerTest.php
I am targetting this branch, because this is a bugfix.
```markdown
- Catch exception when finding post by permalink
```
According to the [PermalinkInterace](https://github.com/sonata-project/SonataNewsBundle/blob/3.x/Permalink/PermalinkInterface.php#L28) an exception could occur. This PR catches the exception so a PostInterface or null will be returns when calling `PostManager::findOneByPermalink`.
> Catch exception when finding post by permalink

- Resources/config/doctrine/Comment.mongodb.xml.skeleton
- Resources/config/doctrine/Comment.orm.xml.skeleton
- Resources/config/doctrine/Post.mongodb.xml.skeleton
- Resources/config/doctrine/Post.orm.xml.skeleton
- composer.json
I am targeting this branch, because my patch is fixing the bug, arisen due to the hardcoded class-path.
```markdown
- Fixed hardcoded paths to classes in `.xml.skeleton` files of config
```
Fixed some hardcoded paths, which become invalid after enabling
the '--namespace' option in SonataEasyExtendsBundle's last release
(https://github.com/sonata-project/SonataEasyExtendsBundle/releases/tag/2.2.0)
See also: https://github.com/sonata-project/SonataMediaBundle/pull/1250
> Fixed paths related to SonataEasyExtendsBundle

- Resources/doc/reference/installation.rst
I am targeting this branch, because this is a docs change.
Based on #339 
Add a note for setting up BlockBundle first, including a link to the docs
> added note to setup block bundle first

- Admin/CommentAdmin.php
- Admin/PostAdmin.php
- Block/RecentCommentsBlockService.php
- Block/RecentPostsBlockService.php
- Form/Type/CommentType.php
- composer.json
```markdown
- Removed usage of old form type aliases
- support for old versions of php and Symfony
```
> Drop old versions of php/sf

- Resources/config/doctrine/BasePost.mongodb.xml
- UPGRADE-3.x.md
I am targeting this branch, because this does not work on this branch regarding to dependencies. NOT: This is a BC break but this needs to be fixed.
Closes #371 
```markdown
- Fixed `Post` Document mongoDb metadata from `comments_count` to `commentsCount`
```
Can you please let me know how to update Docs or add Notes?
> fixed mongoDb metadata config for Post Document #371

- src/Controller/PostController.php
```markdown
- Removed deprecated form alias usage
```
This won't work in symfony 4.x.
> Removed deprecated form alias usage

- src/Resources/views/Post/view.html.twig
```markdown
- Fixed calling deprecated twig tag
```
When using twig 2.0, an error is thrown:
```
[Twig_Error_Syntax]    
Unknown "render" tag.  
```
> Fixed calling deprecated twig tag

- composer.json
```markdown
- Added support fos `sonata-project/user-bundle` 4
```
> Allow sonata user bundle 4.x

- src/Form/Type/CommentStatusType.php
```markdown
- Added missing translation to `CommentStatusType`
```
> Added missing translation to CommentStatusType

- composer.json
- src/Form/Type/CommentStatusType.php
After the back and forth of PHP versions, we lost 7.1 on master, which was not intended. This PR restores it.
> Restore PHP 7.1

- src/Block/Breadcrumb/NewsArchiveBreadcrumbBlockService.php
- src/Block/Breadcrumb/NewsPostBreadcrumbBlockService.php
```markdown
- Don't call the translator in breadcrumbs
```
We don't need to call the translator on user generated content.
> Don't call the translator in breadcrumbs

- src/Form/Type/CommentType.php
```markdown
- Fixed calling deprecated setDefaultOptions method
```
This is patch is needed for symfony 3.
> Fixed calling deprecated setDefaultOptions method

- composer.json
```markdown
- Added support for swiftmailer 6
```
> Allow swiftmailer 6

- src/Mailer/Mailer.php
I am targeting this branch, because this is a bugfix for #426 
```markdown
- Fixed creating new swift message
```
According to https://github.com/swiftmailer/swiftmailer/blob/5f617743a4bf70c2f453efdbc850abe04de6f1af/CHANGES#L30, the method was removed.
> Fixed creating new swift message

- composer.json
- docs/reference/advanced_configuration.rst
- docs/reference/installation.rst
- src/Admin/PostAdmin.php
- src/Block/RecentCommentsBlockService.php
- src/Block/RecentPostsBlockService.php
- src/Controller/PostController.php
- src/Resources/config/admin.xml
- src/Resources/config/block.xml
- src/Resources/config/core.xml
- src/Resources/views/Admin/inner_row_comment.html.twig
- src/Resources/views/Admin/list_post_custom.html.twig
```markdown
- Switch all templates references to Twig namespaced syntax
- Switch from templating service to sonata.templating
```
This PR is a part of a big plan of decoupling sonata-project bundles from Templating Component. See sonata-project/dev-kit#380 for details
> Decouple from Templating Component, Stage 1

- src/Admin/PostAdmin.php
```markdown
- Fixed wrong translation key
```
The translator was using a label instead of an translation key:
> Fixed wrong translation key

- src/Block/RecentCommentsBlockService.php
- src/Block/RecentPostsBlockService.php
- src/Resources/translations/SonataNewsBundle.de.xliff
- src/Resources/translations/SonataNewsBundle.en.xliff
- src/Resources/translations/SonataNewsBundle.fr.xliff
- src/Resources/views/Block/recent_comments.html.twig
- src/Resources/views/Block/recent_posts.html.twig
I am targeting this branch, because this feature is BC (if you ignore the html changes).
```markdown
- added block title translation domain option
- added block icon option
- added block class option
- replaced box with bootstrap panel layout in blocks
- Removed default title from blocks
```
> Added more options to blocks

- src/Controller/PostController.php
Rebase of https://github.com/sonata-project/SonataNewsBundle/pull/434
Closes #433
```markdown
- Fixed calling wrong method when submitting comment
- Check if the comment form was submitted
```
Passing the request to `Form::submit` won't work in symfony 3: https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form
> Use handleRequest instead of submit method

- src/Block/RecentCommentsBlockService.php
- src/Block/RecentPostsBlockService.php
```markdown
- Fixed wrong translation in blocks
```
> Fixed wrong translation in blocks

- src/DependencyInjection/SonataNewsExtension.php
- src/Resources/config/command.xml
I am targeting this branch, because this is a BC fix.
```markdown
- Commands not working on symfony4
```
On symfony4 commands are not working as they are not registered as a services, this fixes it.
> Commands as services

- composer.json
- src/Controller/Api/CommentController.php
- src/Controller/Api/PostController.php
- tests/Controller/Api/PostControllerTest.php
```markdown
- Compatibility with FOSRest 2.0
- Replaced deprecated `bind` by `handleRequest` on forms
```
Since this bundle is not even compatible with FOSRest 2.0 let's add that first before removing compat with 1.0.
Also bind was deprecated like a lot of years ago, instead use handleRequest: https://github.com/symfony/symfony/blob/2.4/UPGRADE-3.0.md#form
This bundle is also waiting for FOSUserBundle to be compatible with 4.0
> Add compatibility with FOSRest 2.0

- src/Resources/views/Post/archive.html.twig
Closes #454
```markdown
- Previous and next links now link to the correct location in the archive page
```
> #454 pagination swap prev-next link destination (fix)

- src/Action/AbstractPostArchiveAction.php
- src/Action/CollectionPostArchiveAction.php
- src/Action/CommentListAction.php
- src/Action/CreateCommentAction.php
- src/Action/CreateCommentFormAction.php
- src/Action/ModerateCommentAction.php
- src/Action/MonthlyPostArchiveAction.php
- src/Action/PostArchiveAction.php
- src/Action/TagPostArchiveAction.php
- src/Action/ViewPostAction.php
- src/Action/YearlyPostArchiveAction.php
- src/Controller/PostController.php
- src/DependencyInjection/SonataNewsExtension.php
- src/Resources/config/actions.xml
- src/Resources/config/routing/news.xml
- src/Resources/views/Post/view.html.twig
```markdown
- `Controller\PostController` is now deprecated in favor of `Action\*Action`
```
Using invokable CaaSes vs one big controller achieves several things:
1. it discourages piling on more actions in controllers with vague names (SRP)
2. it leads to easier to unit test actions and visible deps (DIP)
3. it will allow us to make more services private
Refs https://github.com/sonata-project/SonataAdminBundle/pull/5120
> Use ADR pattern

- src/Action/ViewPostAction.php
- src/Resources/config/actions.xml
- src/Resources/translations/SonataNewsBundle.de.xliff
- src/Resources/translations/SonataNewsBundle.en.xliff
- src/Resources/views/Post/view.html.twig
I am targeting this branch, because this is BC if not tag is created before merging this.
```markdown
- Make posts visible to admins
- Show status message if post is not public
```
This PR makes all posts visible to admins and show a status information:
> Make posts visible to admins with status message

- src/Action/AbstractPostArchiveAction.php
- src/Action/CollectionPostArchiveAction.php
- src/Action/MonthlyPostArchiveAction.php
- src/Action/PostArchiveAction.php
- src/Action/TagPostArchiveAction.php
- src/Action/YearlyPostArchiveAction.php
- src/Resources/config/actions.xml
- src/Resources/translations/SonataNewsBundle.de.xliff
- src/Resources/translations/SonataNewsBundle.en.xliff
I am targeting this branch, because this is BC if not tag is created before merging this.
```markdown
- Added SEO information to archives
```
Adds more SEO information to archive pafges.
> Add SEO information to archives

- src/Resources/config/admin.xml
```markdown
- Added group icon to admin pages
```
> Added admin icons

- src/Resources/config/actions.xml
```markdown
- Added missing seo information to `PostArchiveAction`
```
> Added missing seo information to PostArchiveAction

- docs/reference/advanced_configuration.rst
Remove Tag and Collection from sonata news configuration file otherwise it's just not working :
> Unrecognized  option "tag" under "sonata_news.admin". Available options are "comment", "post".
I am targeting this branch, because this is a documentation fix.
> Documentation : Remove Tag and Collection from sonata news configuration file

- composer.json
- docs/reference/advanced_configuration.rst
- src/DependencyInjection/SonataNewsExtension.php
- tests/DependencyInjection/SonataNewsExtensionTest.php
According the issue #517 we have to add more controls in order to prevent people to forget the tag and the collection class declarations.
That's why I add some information in the documentation and I add a trigger_error message.
Moreover I created a new test class : SonataNewsExtensionTest to test this PR.
I am targeting this branch, because this pull request is backwards comptatible.
Closes #517 , #385 
```markdown
- Added a new test class SonataNewsExtensionTest. Inspired by the SonataMediaExtensionTest, I extended AbstractExtensionTestCase to test if the association with media, user, tag, collection have been created according to a configuration
- A dependency to [matthiasnoback/symfony-dependency-injection-test
](https://packagist.org/packages/matthiasnoback/symfony-dependency-injection …
```
> Trigger an error if a class declaration is missing in the configuration

- docs/reference/installation.rst
Updated missing information about basic setup for "FOS CKEditor" ``news`` context configuration
I am targeting this branch, because there's no information in SonataNewsBundle [setup docs](https://sonata-project.org/bundles/news/3-x/doc/reference/installation.html) about basic [required context in ``PostAdmin.php``] configuration for "FOS CKEditor" bundle.
Closes #482
> [Docs] Missing "FOS CKEditor" default config

- composer.json
- src/Action/CreateCommentAction.php
- src/Event/CommentEvent.php
- src/Event/FilterCommentResponseEvent.php
- src/Event/FormEvent.php
- src/Event/GetResponseCommentEvent.php
- src/Resources/config/actions.xml
- src/SonataNewsEvents.php
Added events to the comment action. This is a great start for custom comment filtering or extending the comment before processing it.
I am targeting this branch, because this feature is BC.
```markdown
- Added events to the comment process 
```
>  Added events to comment action 

- composer.json
- src/Twig/Extension/NewsExtension.php
Fixing Twig deprecation notice in Symfony 4
```markdown
- Add missing `twig/twig` required in `composer.json` with versions `^1.35 || ^2.4`
* deprecation notice about using namespaced classes from `\Twig\`
```
> Twig deprecation notice

- composer.json
- src/Resources/config/block.xml
```markdown
- Add default context to breadcrumbs 
```
> Add default context to breadcrumbs 

- composer.json
By default composer installs v3 and this error occurs:
An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\NewsBundle\Controller\Api\PostController::getPostsAction() does not exist, or could not be auto-loaded in Sonata\NewsBundle\Controller\Api\PostController (which is being imported from "/www/config/routes/routes.yaml").").
I am targeting this branch, because is's a little fix.
```markdown
- Added conflict for unsupported `nelmio/api-doc-bundle` versions
```
> Add nelmio/api-doc-bundle versions conflicts

- composer.json
- src/Controller/Api/PostController.php
- src/DependencyInjection/SonataNewsExtension.php
- src/Model/CommentManagerInterface.php
- src/Model/PostManagerInterface.php
- tests/Document/CommentManagerTest.php
- tests/Document/PostManagerTest.php
Fix deprecation
`The Sonata\Doctrine\Model\PageableManagerInterface class is deprecated since 1.3 in favor of Sonata\DatagridBundle\Pager\PageableInterface, and will be removed in 2.0.`
```markdown
use `Sonata\DatagridBundle\Pager\PageableInterface` instead of `Sonata\Doctrine\Model\PageableManagerInterface`;
```
> use Sonata\DatagridBundle\Pager\PageableInterface;

- composer.json
- docs/reference/installation.rst
- src/Admin/PostAdmin.php
- src/Model/Post.php
- src/Model/PostInterface.php
- src/Resources/config/doctrine_mongodb_admin.xml
- src/Resources/config/doctrine_orm_admin.xml
- tests/DependencyInjection/SonataNewsExtensionTest.php
- tests/Fixtures/UserMock.php
We don't need FOS or Sonata UserBundle, we can use the symfony UserInterface for everything.
```markdown
- Removed tight coupling to user bundle
- Removed `sonata-project/user-bundle` dependency
```
> Remove tight coupling to user bundle

- composer.json
Allow using the bundle as a (frontend) bundle only.
There is already a check for a loaded AdminBundle, but the AdminBundle was required by composer.
https://github.com/sonata-project/SonataNewsBundle/blob/3.x/src/DependencyInjection/SonataNewsExtension.php#L61-L63
```markdown
- Make admin bundle optional
```
> Make admin bundle optional

- src/Resources/views/Post/archive.rss.twig
There is a problem when calling `format_datetime` when you use SonataIntlBundle and TwigIntlBundle. Both bundles provide a `format_datetime` filter with a different signature.
```markdown
- Fix clashing `format_datetime` filter call
```
> Fix clashing date filter call

- composer.json
- src/DependencyInjection/SonataNewsExtension.php
- src/Resources/views/Admin/list_post_custom.html.twig
- src/Resources/views/Block/recent_comments.html.twig
- tests/DependencyInjection/SonataNewsExtensionTest.php
This bundle was using `truncate` filter without explicitly require `twig/extensions`, with this PR it uses `u` filter.
I added `twig/extra-bundle` to autoload the Twig extension and a fallback in case Flex is not used.
Ref: sonata-project/SonataAdminBundle#6132
I am targeting this branch, because these changes are BC.
```markdown
- Added `twig/string-extra` dependency.
- Changed use of `truncate` filter with `u` filter.
```
> Replace truncate filter with u filter

- src/DependencyInjection/Compiler/TwigStringExtensionCompilerPass.php
- src/DependencyInjection/SonataNewsExtension.php
- src/SonataNewsBundle.php
- tests/DependencyInjection/Compiler/TwigStringExtensionCompilerPassTest.php
- tests/DependencyInjection/SonataNewsExtensionTest.php
This PR contains:
- move StringExtension registration to Compiler pass and check all `twig.extension` service to avoid duplication
- improve tests
- fix previus broken checking
```php
... !is_a($container->getDefinition('twig.extension.string')->getClass(), StringExtension::class)) ...
// it is like this:   !is_a('Twig\Extra\String\StringExtension', StringExtension::class)) ...
```
I am targeting this branch, because this change respect BC.
PATCH for  non release #602.
> Fix StringExtension registration

- composer.json
- src/SonataNewsBundle.php
- tests/App/AppKernel.php
- tests/App/Controller/TruncateController.php
- tests/App/Resources/views/truncate_test.html.twig
- tests/App/config/config.yaml
- tests/App/config/routes.yaml
- tests/App/config/security.yaml
- tests/App/config/sonata.yaml
- tests/Functional/Controller/TruncateControllerTest.php
This PR fix case when `TwigStringExtensionCompilerPass` is build after `TwigEnvironmentPass` - then `u` filter is not registred.
I am targeting this branch, because it is PATCH.
```markdown
- Fix missing `u` filter when `SonataNewsBundle` is register after `TwigBundle`
```
> Fix TwigStringExtensionCompilerPass priority

- composer.json
Both datagrid version can be used becouse `PageableInteface` is not used. When we remove deprecated from `PageableManagerInterface` then lower version should be drop with little BC-break.
I am targeting this branch, because this change respect BC.
```markdown
- support for sonata-project/datagrid-bundle v3
```
> Add support for sonata-project/datagrid-bundle v3

- UPGRADE-4.0.md
- src/Action/AbstractPostArchiveAction.php
- src/Action/CommentListAction.php
- src/Action/CreateCommentAction.php
- src/Action/CreateCommentFormAction.php
- src/Action/ViewPostAction.php
- src/Controller/PostController.php
- src/Document/CommentManager.php
- src/Document/PostManager.php
- src/Entity/CommentManager.php
- src/Entity/PostManager.php
- tests/Controller/Api/PostControllerTest.php
- tests/Functional/Controller/TruncateControllerTest.php
Unfortunately it's easier to open a new PR than rebasing the #646 branch, then this is the follow up.
Remove some deprecations:
- using SF4.2 `AbstractController`
- using SF4.3 `HttpKernelBrowser`
- using `Sonata\DatagridBundle\Pager\PageableInterface`
I am targeting master, because for the many BC break (#646 )
```markdown
- Deprecated usage of `Symfony\Component\HttpKernel\Client`
- Deprecated usage of `Symfony\Bundle\FrameworkBundle\Controller\Controller`
- Deprecated usage of `Sonata\Doctrine\Model\PageableManagerInterface`
```
> ♻️  Remove some deprecations

- tests/Action/DailyPostArchiveActionTest.php
I am targeting this branch, because this is pedantic.
> Remove deprecations from PHPUnit 9

- UPGRADE-3.x.md
- composer.json
- src/Mailer/Mailer.php
- tests/Mailer/MailerTest.php
Allow to use "symfony/mailer" within Mailer.
I am targeting this branch, because this change respects BC.
```markdown
- Support for "symfony/mailer" in `Sonata\NewsBundle\Mailer\Mailer`.
- Support for "swiftmailer/swiftmailer" in `Sonata\NewsBundle\Mailer\Mailer`.
```
> Allow to use "symfony/mailer" within `Mailer`
